services:
  app:
    build:
        context: .
        dockerfile: docker/smilephoto/Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: app
          target: /app
          ignore:
            - node_modules
            - .next
        - action: rebuild
          path: requirements.txt
